# Generated by Django 5.0 on 2023-12-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='block',
            field=models.ManyToManyField(related_name='blocked', to='social.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='social.userprofile'),
        ),
    ]
