# Generated by Django 5.0 on 2023-12-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userprofile_block_alter_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='block',
            field=models.ManyToManyField(null=True, related_name='blocked', to='social.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(null=True, related_name='followed_by', to='social.userprofile'),
        ),
    ]
